import type { Transfer, AccountInfo } from './subscan';
import type { RiskScore } from './risk-scoring';
import { getRiskLabel } from './risk-scoring';
import { getChain } from './chains';
import { formatTimestamp, truncateAddress, formatNumber } from './explorer-utils';
import { lookupAddress } from './known-addresses';
import { getAllNotes } from './forensic-notes';

interface SummaryInput {
  address: string;
  chain: string;
  accountInfo: AccountInfo | null;
  transfers: Transfer[];
  riskScore: RiskScore;
  stats: {
    totalSent: number;
    totalReceived: number;
    sentCount: number;
    recvCount: number;
    counterparties: number;
    firstSeen: number | null;
    lastSeen: number | null;
  };
  contractStatus?: string | null;
}

export function generateInvestigationSummary(input: SummaryInput): string {
  const { address, chain, accountInfo, transfers, riskScore, stats, contractStatus } = input;
  const chainConfig = getChain(chain);
  const symbol = chainConfig.tokenSymbol;
  const now = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

  // Notes for this address
  const notes = getAllNotes().filter(n => n.targetId.toLowerCase() === address.toLowerCase());

  // Top counterparties
  const cpMap = new Map<string, { volume: number; count: number }>();
  const addr = address.toLowerCase();
  for (const t of transfers) {
    const cp = t.from.toLowerCase() === addr ? t.to : t.from;
    if (cp.toLowerCase() === addr) continue;
    const existing = cpMap.get(cp.toLowerCase()) || { volume: 0, count: 0 };
    existing.volume += parseFloat(t.amount || '0');
    existing.count++;
    cpMap.set(cp.toLowerCase(), existing);
  }
  const topCPs = Array.from(cpMap.entries())
    .sort((a, b) => b[1].volume - a[1].volume)
    .slice(0, 10);

  // Recent transfers
  const recentTxs = transfers.slice(0, 20);

  let md = `# Investigation Summary
Generated: ${now}
Tool: HubSec Forensic Explorer (hubsec.net/explorer)

## Target Account
- **Address:** \`${address}\`
- **Chain:** ${chainConfig.name}
- **Risk Assessment:** ${riskScore.overall}/100 (${getRiskLabel(riskScore.overall)})
`;

  if (contractStatus) {
    md += `- **Account Type:** ${contractStatus}\n`;
  }

  const known = lookupAddress(address);
  if (known) {
    md += `- **Known Tag:** ${known.tag} (${known.category})\n`;
  }

  md += `
## Profile
| Metric | Value |
|--------|-------|
| Balance | ${formatNumber(accountInfo?.balance || '0')} ${symbol} |
| Total Sent | ${formatNumber(stats.totalSent.toFixed(2))} ${symbol} |
| Total Received | ${formatNumber(stats.totalReceived.toFixed(2))} ${symbol} |
| Tx Count | ${stats.sentCount + stats.recvCount} (sent: ${stats.sentCount}, recv: ${stats.recvCount}) |
| Counterparties | ${stats.counterparties} unique |
| First Transfer | ${stats.firstSeen ? formatTimestamp(stats.firstSeen) : 'N/A'} |
| Last Transfer | ${stats.lastSeen ? formatTimestamp(stats.lastSeen) : 'N/A'} |
`;

  // Risk factors
  if (riskScore.factors.length > 0) {
    md += `\n## Risk Factors\n`;
    for (const f of riskScore.factors) {
      md += `- **${f.name}** (+${f.score}): ${f.description}\n`;
    }
  } else {
    md += `\n## Risk Factors\nNo risk factors detected.\n`;
  }

  // Top counterparties
  if (topCPs.length > 0) {
    md += `\n## Top Counterparties\n`;
    md += `| # | Address | Tag | Volume (${symbol}) | Txs |\n`;
    md += `|---|---------|-----|----------|-----|\n`;
    topCPs.forEach(([cpAddr, data], i) => {
      const cpKnown = lookupAddress(cpAddr);
      md += `| ${i + 1} | \`${truncateAddress(cpAddr, 10, 8)}\` | ${cpKnown?.tag || '—'} | ${data.volume.toFixed(4)} | ${data.count} |\n`;
    });
  }

  // Investigator notes
  if (notes.length > 0) {
    md += `\n## Investigator Notes\n`;
    for (const n of notes) {
      md += `- "${n.text}" _(${new Date(n.createdAt).toISOString().slice(0, 10)})_\n`;
    }
  }

  // Recent transactions
  if (recentTxs.length > 0) {
    md += `\n## Recent Transactions (last ${recentTxs.length})\n`;
    md += `| Time | Direction | Counterparty | Amount | Token | Hash |\n`;
    md += `|------|-----------|-------------|--------|-------|------|\n`;
    for (const t of recentTxs) {
      const dir = t.from.toLowerCase() === addr ? 'OUT' : 'IN';
      const cp = t.from.toLowerCase() === addr ? t.to : t.from;
      const cpKnown = lookupAddress(cp);
      md += `| ${formatTimestamp(t.block_timestamp)} | ${dir} | ${cpKnown?.tag || truncateAddress(cp, 8, 6)} | ${parseFloat(t.amount || '0').toFixed(4)} | ${t.asset_symbol || symbol} | \`${truncateAddress(t.hash || '', 8, 6)}\` |\n`;
    }
  }

  md += `\n---\n*Generated by HubSec Forensic Explorer. This report reflects data available at the time of generation and may not be complete.*\n`;

  return md;
}

export function downloadSummary(markdown: string, address: string): void {
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `investigation_${address.slice(0, 10)}_${new Date().toISOString().slice(0, 10)}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
